version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Ensure the correct Node.js version
    commands:
      - cd web-tier
      - npm ci  # Faster & more reliable than npm install

  build:
    commands:
      - npm run build  # Builds your React app

artifacts:
  files:
    - '**/*'
  base-directory: web-tier/build
