version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - cd web-tier && npm install
      - cd ../app-tier && npm install

  build:
    commands:
      - echo "Building the React frontend..."
      - cd ../web-tier && npm run build
      - echo "Packaging application..."
      - cd ../ && zip -r deploy.zip web-tier/ app-tier/

artifacts:
  files:
    - deploy.zip
